version: '3.4'

services:
  librarymanager.database:
    image: "mcr.microsoft.com/mssql/server:2025-latest"
    container_name: librarymanager.database
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345
    volumes:
      - "sqlvolume:/var/opt/mssql"
    networks:
      - librarymanager.network
    restart: always

  librarymanager.api:
    image: ${DOCKER_REGISTRY-}librarymanagerapi
    container_name: librarymanager.api
    build:
      context: .
      dockerfile: LibraryManager.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - librarymanager.database
    restart: on-failure
    networks:
      - librarymanager.network

networks:
  librarymanager.network:
    
volumes:
  sqlvolume: